version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "dependabot"
      include: "scope"
